if [ "${UBIENV_OS}" != "Darwin" ]; then
  return
fi
if [ "${BREW_HOME}" == "" ]; then
  export BREW_HOME="${TOOLS_DIR}/homebrew"
fi
if [ ! -d "${BREW_HOME}/bin" ]; then
  ubienv::err "Could not find homebrew in ${BREW_HOME}"
  return
fi
export PATH="${BREW_HOME}/bin:${PATH}"
