export NODE_JS_VER="v0.8.25"  # Latest maintenance release

if [ -d ${TOOLS_DIR}/nvm/${NODE_JS_VER} ]; then
  export NODE_PATH="${TOOLS_DIR}/nvm/${NODE_JS_VER}/lib/node_modules"
  export PATH="$PATH:${TOOLS_DIR}/nvm/${NODE_JS_VER}/bin"
else
  ubienv::err "nvm / node don't seem to be installed."
fi
